addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.6.0")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.1")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"    % "1.1.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"      % "1.2.0")
