name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags-ignore:
      - v*

jobs:
  build:
    name: Code Style, Tests, Documentation
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.1.2
        with:
          jvm: adopt:11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: "Code style, tests, documentation"
        run: sbt "scalafmtCheckAll; scalafmtSbtCheck; test; doc"
